[package]
name = "hrpc"
version = "0.2.3"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/harmony-development/hrpc-rs"
homepage = "https://github.com/harmony-development/hrpc-rs"
description = "Common code for hRPC."
keywords = ["hrpc", "harmony", "rpc"]

[dependencies]
prost = "0.7"
bytes = "1.0"
tokio = "1.2"
tokio-rustls = "0.22"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls-native-roots"] }
url = "2.2"
async-tungstenite = { version = "0.13", features = ["tokio-rustls"] }
futures-util = "0.3"
