[package]
name = "hrpc"
version = "0.28.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/harmony-development/hrpc-rs"
homepage = "https://github.com/harmony-development/hrpc-rs"
description = "Common code for hRPC."
keywords = ["hrpc", "harmony", "rpc", "protobuf"]
categories = ["network-programming"]
include = [
    "/src",
    "/build.rs",
    "/Cargo.toml",
    "/hrpc-main/protocol",
    "/README.md",
]

[package.metadata.docs.rs]
all-features = true

[package.metadata.nix]
build = true
library = true

[features]
default = []

# Recommended transport
recommended = ["http_server", "http_client"]

server = [
    "tokio/sync",
    "tokio/rt",
    "tokio/macros",
    "tokio/time",
    "matchit",
    "hrpc-proc-macro",
    "flume",
]
client = ["tokio/sync", "tokio/rt", "tokio/macros", "flume"]
disable_socket_auto_ping = []

# HTTP transport
http_server = [
    "http",
    "http-body",
    "hyper",
    "axum-server",
    "hyper/server",
    "tokio-tungstenite",
    "sha-1",
    "base64",
]
http_client = [
    "http",
    "http-body",
    "rustls-native-certs",
    "tokio-rustls",
    "tokio-tungstenite",
    "hyper",
    "hyper-rustls",
    "hyper/client",
]

[build-dependencies]
# Needed to compile the hRPC proto
hrpc-build = { version = "0.28.0", path = "../hrpc-build", default-features = false }
prost-build = "0.9"

[dependencies]
# Core types, traits and utilities
prost = "0.9"
bytes = "1.0"
http = { version = "0.2", optional = true }
http-body = { version = "0.4", optional = true }
futures-util = { version = "0.3", default-features = false, features = [
    "std",
    "sink",
] }
hrpc-proc-macro = { version = "0.28.0", path = "../hrpc-proc-macro", optional = true }
tower = { version = "0.4", default-features = false, features = ["util"] }

# Logging
tracing = { version = "0.1", default-features = false, features = ["std"] }

# Our async runtime
tokio = { version = "1.8", default-features = false, features = [
    "parking_lot",
] }

# Networking!
hyper = { version = "0.14", default-features = false, features = [
    "http1",
    "http2",
    "runtime",
    "stream",
], optional = true }
hyper-rustls = { version = "0.22", default-features = false, features = [
    "native-tokio",
], optional = true }
tokio-tungstenite = { version = "0.15", default-features = false, features = [
    "rustls-tls",
], optional = true }
axum-server = { version = "0.3", default-features = false, features = ["tls-rustls"], optional = true }

# Only used by client to discover certs for WS
rustls-native-certs = { version = "0.5", default-features = false, optional = true }
# Used by client to connect with TLS
tokio-rustls = { version = "0.22", default-features = false, optional = true }

# Used by server for routing
matchit = { version = "0.4", default-features = false, optional = true }

# Used by server to implement WS request handling
sha-1 = { version = "0.9", default-features = false, optional = true }
base64 = { version = "0.13", default-features = false, optional = true }

# Overall better locks
parking_lot = { version = "0.11", default-features = false }
# Used in socket impls
flume = { version = "0.10", default-features = false, features = [
    "async",
    # TODO(yusdacra): Do we need eventual fairness?
    "eventual-fairness",
], optional = true }
