name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler
    - name: Install rust
      run: rustup default stable && rustup update && rustup component add rustfmt clippy

    - name: Cache rust
      uses: Swatinem/rust-cache@v1

    - name: Clippy (Common hrpc)
      uses: actions-rs/clippy-check@v1
      with:
        args: --package hrpc --features server,client
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build (Common hrpc)
      run: cargo build --package hrpc --features server,client --verbose

    - name: Test (Common hrpc)
      run: RUST_LOG=info cargo test --package hrpc --features server,client --verbose

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        args: --all-targets
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: cargo build --all-targets --verbose

    - name: Test
      run: RUST_LOG=info cargo test --all-targets --verbose
    
    - name: Doc
      run: cargo doc --no-deps --all-features --verbose

    - name: Finalize documentation
      run: |
        CRATE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
        echo "<meta http-equiv=\"refresh\" content=\"0; url=hrpc\">" > target/doc/index.html
        touch target/doc/.nojekyll

    - name: Publish docs
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc/
        publish_branch: gh-pages
